# apiVersion: apps/v1
# kind: StatefulSet
# metadata:
#   name: postgres-operational-db
#   namespace: airflow-tt-v2
#   labels:
#     app: postgres-operational
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: postgres-operational
#   serviceName: "postgres-operational-service"
#   template:
#     metadata:
#       labels:
#         app: postgres-operational
#     spec:
#       initContainers:
#       - name: init-db-operational
#         image: postgres:15
#         command: ["/bin/bash", "-c"]
#         args:
#           - |
#             for script in /scripts/sql-scripts/operational/*.sql; do
#               echo "Running $script";
#               psql -U $POSTGRES_USER -d $POSTGRES_DB -f $script;
#             done
#         env:
#           - name: POSTGRES_USER
#             valueFrom:
#               secretKeyRef:
#                 name: postgres-operational-secret
#                 key: user
#           - name: POSTGRES_PASSWORD
#             valueFrom:
#               secretKeyRef:
#                 name: postgres-operational-secret
#                 key: password
#           - name: POSTGRES_DB
#             valueFrom:
#               secretKeyRef:
#                 name: postgres-operational-secret
#                 key: db
#         volumeMounts:
#           - name: init-scripts
#             mountPath: /scripts    
#       containers:
#       - name: postgres-operational
#         image: postgres:15
#         ports:
#         - containerPort: 5432
#         env:
#         - name: POSTGRES_USER
#           valueFrom:
#             secretKeyRef:
#               name: postgres-operational-secret
#               key: user
#         - name: POSTGRES_PASSWORD
#           valueFrom:
#             secretKeyRef:
#               name: postgres-operational-secret
#               key: password
#         - name: POSTGRES_DB
#           valueFrom:
#             secretKeyRef:
#               name: postgres-operational-secret
#               key: db
#         volumeMounts:
#         - name: postgres-storage
#           mountPath: /var/lib/postgresql/data
#       volumes:
#       - name: init-scripts
#         configMap:
#           name: postgres-operational-scripts
#   volumeClaimTemplates:
#   - metadata:
#       name: postgres-storage
#     spec:
#       accessModes:
#       - ReadWriteOnce
#       resources:
#         requests:
#           storage: 5Gi

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-operational-db
  namespace: airflow-tt-v2
  labels:
    app: postgres-operational
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-operational
  serviceName: "postgres-operational-service"
  template:
    metadata:
      labels:
        app: postgres-operational
    spec:
      # initContainers:
      # - name: init-db-operational
      #   image: postgres:15
      #   command: ["/bin/bash", "-c"]
      #   args:
      #     - |
      #       for script in /scripts/sql-scripts/operational/*.sql; do
      #         echo "Running $script";
      #         psql -U $POSTGRES_USER -d $POSTGRES_DB -f $script;
      #       done
      #   env:
      #     - name: POSTGRES_USER
      #       valueFrom:
      #         secretKeyRef:
      #           name: postgres-operational-secret
      #           key: user
      #     - name: POSTGRES_PASSWORD
      #       valueFrom:
      #         secretKeyRef:
      #           name: postgres-operational-secret
      #           key: password
      #     - name: POSTGRES_DB
      #       valueFrom:
      #         secretKeyRef:
      #           name: postgres-operational-secret
      #           key: db
      #   volumeMounts:
      #     - name: init-scripts
      #       mountPath: /scripts
      containers:
      - name: postgres-operational
        image: postgres:15
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-operational-secret
              key: user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-operational-secret
              key: password
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: postgres-operational-secret
              key: db
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: postgres-storage
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
