apiVersion: v1
kind: Secret
metadata:
  name: postgres-operational-secret
type: Opaque
data:
  user: cG9zdGdyZXM=   # postgres (в base64)
  password: bXlzZWNyZXRwYXNzd29yZA==   # mysecretpassword (в base64)
  db: dGVzdF9vcGVyYXRpb25hbA==   # test_operational (в base64)

---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-analytics-secret
type: Opaque
data:
  user: cG9zdGdyZXM=   # postgres (в base64)
  password: bXlzZWNyZXRwYXNzd29yZA==   # mysecretpassword (в base64)
  db: dGVzdF9hbmFseXRpY3M=   # test_analytics (в base64)